<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.1							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      es	   CDATA #IMPLIED
	      em	   CDATA #IMPLIED
	      ep	   CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.1">
<Header n="laghos">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="laghos">
<SecHeader>
  <MetricTable>
    <Metric i="0" n="REALTIME (usec).[511,0]" v="raw" em="0" es="0" ep="0" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="1"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" db-glob="*.hpctrace" db-min-time="1561477259156630" db-max-time="1561477477376668" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/lustre/atlas2/csc322/scratch/laiwei2/laghos/laghos"/>
    <LoadModule i="319566" n="&lt;unknown load module&gt;"/>
    <LoadModule i="319575" n="/lustre/atlas2/csc322/scratch/laiwei2/install/hpctoolkit/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="319583" n="/lib64/librt-2.11.3.so"/>
    <LoadModule i="319587" n="/opt/cray/mpt/7.6.3/gni/mpich-gnu/5.1/lib/libmpich_gnu_51.so.3.0.1"/>
    <LoadModule i="319752" n="/lib64/libm-2.11.3.so"/>
    <LoadModule i="319780" n="/lib64/libpthread-2.11.3.so"/>
    <LoadModule i="319790" n="/opt/gcc/7.3.0/snos/lib64/libstdc++.so.6.0.24"/>
    <LoadModule i="319855" n="/lib64/libc-2.11.3.so"/>
    <LoadModule i="319899" n="/lustre/atlas2/csc322/scratch/laiwei2/install/hpctoolkit/lib/hpctoolkit/ext-libs/liblzma.so.5.2.4"/>
    <LoadModule i="319905" n="/lib64/ld-2.11.3.so"/>
    <LoadModule i="319913" n="/opt/cray/ugni/6.0-1.0502.10863.8.28.gem/lib64/libugni.so.0.6.0"/>
    <LoadModule i="319933" n="/opt/cray/udreg/2.3.2-1.0502.10518.2.17.gem/lib64/libudreg.so.0.2.3"/>
    <LoadModule i="319939" n="/opt/cray/pmi/5.0.12/lib64/libpmi.so.0.5.0"/>
    <LoadModule i="319973" n="/opt/cray/alps/5.2.4-2.0502.9950.37.1.gem/lib64/libalpslli.so.0.0.0"/>
  </LoadModuleTable>
  <FileTable>
    <File i="60859" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/hypre-2.10.0b/src/parcsr_mv/new_commpkg.c"/>
    <File i="62603" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/hypre-2.10.0b/src/parcsr_mv/par_csr_communication.c"/>
    <File i="65163" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/hypre-2.10.0b/src/parcsr_mv/par_csr_matrix.c"/>
    <File i="67909" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/hypre-2.10.0b/src/utilities/exchange_data.c"/>
    <File i="68996" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/hypre-2.10.0b/src/utilities/mpistubs.c"/>
    <File i="76342" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/bilinearform.cpp"/>
    <File i="77055" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fespace.hpp"/>
    <File i="78367" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/bilininteg.cpp"/>
    <File i="79331" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/eltrans.hpp"/>
    <File i="82985" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/coefficient.cpp"/>
    <File i="90090" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/eltrans.cpp"/>
    <File i="93562" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe.cpp"/>
    <File i="110864" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/vector.hpp"/>
    <File i="104085" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/densemat.hpp"/>
    <File i="103896" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe.hpp"/>
    <File i="117971" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe_coll.cpp"/>
    <File i="120870" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe_coll.hpp"/>
    <File i="123809" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fespace.cpp"/>
    <File i="124624" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/array.hpp"/>
    <File i="130456" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/geom.cpp"/>
    <File i="130460" n="./src/opt/gcc/7.3.0/snos/include/g++/iostream"/>
    <File i="133840" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/gridfunc.cpp"/>
    <File i="151801" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pbilinearform.cpp"/>
    <File i="154488" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pfespace.cpp"/>
    <File i="159670" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pfespace.hpp"/>
    <File i="154508" n="./src/opt/gcc/7.3.0/snos/include/g++/bits/stl_algobase.h"/>
    <File i="162879" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pgridfunc.cpp"/>
    <File i="168347" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/array.cpp"/>
    <File i="171207" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/sparsemat.cpp"/>
    <File i="172000" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/communication.cpp"/>
    <File i="176804" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/communication.hpp"/>
    <File i="179702" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/gzstream.cpp"/>
    <File i="183364" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/stable3d.cpp"/>
    <File i="183957" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/table.cpp"/>
    <File i="184131" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/table.hpp"/>
    <File i="185960" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/tic_toc.cpp"/>
    <File i="186125" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/blockvector.cpp"/>
    <File i="186404" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/densemat.cpp"/>
    <File i="186656" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/matrix.hpp"/>
    <File i="186658" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/operator.hpp"/>
    <File i="196821" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/hypre.cpp"/>
    <File i="204249" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/ode.cpp"/>
    <File i="205395" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/operator.cpp"/>
    <File i="207435" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/solvers.cpp"/>
    <File i="211696" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/general/mem_alloc.hpp"/>
    <File i="213818" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/sparsemat.hpp"/>
    <File i="218359" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/vector.cpp"/>
    <File i="219527" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/mesh/mesh.cpp"/>
    <File i="234273" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/mesh/mesh.hpp"/>
    <File i="233870" n="./src/opt/gcc/7.3.0/snos/include/g++/istream"/>
    <File i="267759" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/mesh/pmesh.cpp"/>
    <File i="293831" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/laghos.cpp"/>
    <File i="296398" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/laghos_assembly.cpp"/>
    <File i="299429" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/laghos_assembly.hpp"/>
    <File i="299481" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/laghos_solver.cpp"/>
    <File i="302178" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pgridfunc.hpp"/>
    <File i="302181" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/fem/gridfunc.hpp"/>
    <File i="301729" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/solvers.hpp"/>
    <File i="300284" n="./src/autofs/nccs-svm1_home1/laiwei2/applications/laghos/laghos_solver.hpp"/>
    <File i="319048" n="/usr/src/packages/BUILD/glibc-2.11.3/csu/../sysdeps/x86_64/elf/start.S"/>
    <File i="319062" n="/usr/src/packages/BUILD/glibc-2.11.3/csu/elf-init.c"/>
    <File i="319073" n="&lt;unknown file&gt; [laghos]"/>
    <File i="319572" n="&lt;unknown file&gt;"/>
    <File i="319567" n="&lt;unknown file&gt;"/>
    <File i="319576" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="319584" n="&lt;unknown file&gt; [librt-2.11.3.so]"/>
    <File i="319588" n="&lt;unknown file&gt; [libmpich_gnu_51.so.3.0.1]"/>
    <File i="319617" n="gni_poll.c"/>
    <File i="319624" n="ch3_progress.c"/>
    <File i="319653" n="gni_send.c"/>
    <File i="319746" n="finalize.c"/>
    <File i="319749" n="handlemem.c"/>
    <File i="319753" n="&lt;unknown file&gt; [libm-2.11.3.so]"/>
    <File i="319781" n="&lt;unknown file&gt; [libpthread-2.11.3.so]"/>
    <File i="319791" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/bits/fstream.tcc"/>
    <File i="319794" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/src/c++98/basic_file.cc"/>
    <File i="319797" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/dyncast.cc"/>
    <File i="319800" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/si_class_type_info.cc"/>
    <File i="319804" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/streambuf"/>
    <File i="319811" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/new_op.cc"/>
    <File i="319818" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/vmi_class_type_info.cc"/>
    <File i="319821" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/class_type_info.cc"/>
    <File i="319825" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/del_op.cc"/>
    <File i="319828" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/new_opv.cc"/>
    <File i="319831" n="&lt;unknown file&gt; [libstdc++.so.6.0.24]"/>
    <File i="319843" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/del_opv.cc"/>
    <File i="319849" n="/b/tmp/peint/build-cray-gcc-20180126.202153.829775000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/typeinfo"/>
    <File i="319856" n="&lt;unknown file&gt; [libc-2.11.3.so]"/>
    <File i="319900" n="&lt;unknown file&gt; [liblzma.so.5.2.4]"/>
    <File i="319906" n="&lt;unknown file&gt; [ld-2.11.3.so]"/>
    <File i="319914" n="&lt;unknown file&gt; [libugni.so.0.6.0]"/>
    <File i="319934" n="&lt;unknown file&gt; [libudreg.so.0.2.3]"/>
    <File i="319940" n="&lt;unknown file&gt; [libpmi.so.0.5.0]"/>
    <File i="319943" n="crtstuff.c"/>
    <File i="319946" n="/notbackedup/tmp/ulib/mpt_base/pmi/src/pmi_core/_pmi_init.c"/>
    <File i="319953" n="/notbackedup/tmp/ulib/mpt_base/pmi/src/alps/alps_utils.c"/>
    <File i="319959" n="/notbackedup/tmp/ulib/mpt_base/pmi/src/pmi_core/daemon.c"/>
    <File i="319965" n="/notbackedup/tmp/ulib/mpt_base/pmi/src/pmi_core/smp_barrier.c"/>
    <File i="319974" n="&lt;unknown file&gt; [libalpslli.so.0.0.0]"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="60951" n="hypre_NewCommPkgCreate_core" v="0x7061b0"/>
    <Procedure i="62814" n="hypre_MatvecCommPkgCreate" v="0x708300"/>
    <Procedure i="65189" n="hypre_ParCSRMatrixCreate" v="0x710cb0"/>
    <Procedure i="65555" n="hypre_ParCSRMatrixGetLocalRange" v="0x712000"/>
    <Procedure i="67939" n="hypre_DataExchangeList" v="0x730188"/>
    <Procedure i="69129" n="hypre_MPI_Iprobe" v="0x733e50"/>
    <Procedure i="69134" n="hypre_MPI_Test" v="0x733e70"/>
    <Procedure i="77002" n="mfem::BilinearForm::Assemble" v="0x56f3f0"/>
    <Procedure i="77054" n="" v="0"/>
    <Procedure i="77055" n="mfem::FiniteElementSpace::GetElementTransformation(int) const" v="0"/>
    <Procedure i="79303" n="mfem::MassIntegrator::AssembleElementMatrix" v="0x575a90"/>
    <Procedure i="79330" n="" v="0"/>
    <Procedure i="79331" n="mfem::ElementTransformation::Weight()" v="0"/>
    <Procedure i="80616" n="mfem::VectorMassIntegrator::AssembleElementMatrix" v="0x57a9c0"/>
    <Procedure i="83032" n="mfem::FunctionCoefficient::Eval" v="0x584840"/>
    <Procedure i="82997" n="mfem::GridFunctionCoefficient::Eval" v="0x5846e8"/>
    <Procedure i="83224" n="mfem::VectorFunctionCoefficient::Eval" v="0x585190"/>
    <Procedure i="90241" n="mfem::ElementTransformation::EvalWeight" v="0x594890"/>
    <Procedure i="90246" n="" v="0"/>
    <Procedure i="90247" n="mfem::ElementTransformation::Jacobian()" v="0"/>
    <Procedure i="90250" n="mfem::IsoparametricTransformation::EvalJacobian()" v="0"/>
    <Procedure i="90123" n="mfem::IsoparametricTransformation::EvalJacobian" v="0x594340"/>
    <Procedure i="93224" n="mfem::IsoparametricTransformation::Transform" v="0x599660"/>
    <Procedure i="95621" n="mfem::NodalFiniteElement::Project" v="0x5ae648"/>
    <Procedure i="95894" n="mfem::NodalFiniteElement::Project" v="0x5af420"/>
    <Procedure i="103146" n="mfem::Poly_1D::Basis::Eval" v="0x5cf8f0"/>
    <Procedure i="103933" n="mfem::Poly_1D::Basis::Eval" v="0x5d3560"/>
    <Procedure i="103073" n="mfem::Poly_1D::Binom" v="0x5cf3f0"/>
    <Procedure i="103121" n="mfem::Poly_1D::CalcBinomTerms" v="0x5cf550"/>
    <Procedure i="110821" n="mfem::H1_QuadrilateralElement::H1_QuadrilateralElement" v="0x5f6f28"/>
    <Procedure i="110863" n="" v="0"/>
    <Procedure i="110864" n="mfem::Vector::Vector()" v="0"/>
    <Procedure i="103260" n="mfem::H1_HexahedronElement::CalcShape" v="0x5d0610"/>
    <Procedure i="104063" n="mfem::H1_HexahedronElement::CalcDShape" v="0x5d4930"/>
    <Procedure i="104085" n="mfem::DenseMatrix::operator()(int, int)" v="0"/>
    <Procedure i="109995" n="mfem::H1_TriangleElement::H1_TriangleElement" v="0x5f2640"/>
    <Procedure i="110651" n="mfem::H1_WedgeElement::H1_WedgeElement" v="0x5f5a48"/>
    <Procedure i="103330" n="mfem::L2_HexahedronElement::CalcShape" v="0x5d0e70"/>
    <Procedure i="103868" n="mfem::L2Pos_HexahedronElement::CalcShape" v="0x5d2d90"/>
    <Procedure i="103896" n="mfem::Poly_1D::CalcBernstein(int, double, double*)" v="0"/>
    <Procedure i="103898" n="mfem::Poly_1D::CalcBinomTerms(int, double, double, double*)" v="0"/>
    <Procedure i="93563" n="_GLOBAL__sub_I__ZN4mfem13FiniteElementC2EiNS_8Geometry4TypeEiii" v="0x40b960"/>
    <Procedure i="93566" n="__static_initialization_and_destruction_0" v="0"/>
    <Procedure i="119069" n="mfem::H1_FECollection::H1_FECollection" v="0x59d468"/>
    <Procedure i="121387" n="mfem::H1_FECollection::FiniteElementForGeometry" v="0x5a39e0"/>
    <Procedure i="121393" n="mfem::L2_FECollection::FiniteElementForGeometry" v="0x5a3a10"/>
    <Procedure i="124455" n="mfem::FiniteElementSpace::GetOrder" v="0x60efd0"/>
    <Procedure i="124551" n="mfem::FiniteElementSpace::DofsToVDofs" v="0x60f9a0"/>
    <Procedure i="124592" n="mfem::FiniteElementSpace::GetElementVDofs" v="0x60fb00"/>
    <Procedure i="124596" n="" v="0"/>
    <Procedure i="124597" n="mfem::FiniteElementSpace::DofsToVDofs(mfem::Array&lt;int&gt;&amp;, int) const" v="0"/>
    <Procedure i="124598" n="&lt;inline&gt;" f="1" v="0"/>
    <Procedure i="124603" n="void mfem::Ordering::DofsToVDofs&lt;(mfem::Ordering::Type)0&gt;(int, int, mfem::Array&lt;int&gt;&amp;)" v="0"/>
    <Procedure i="124624" n="mfem::Array&lt;int&gt;::SetSize(int)" v="0"/>
    <Procedure i="125133" n="mfem::FiniteElementSpace::BuildElementToDofTable" v="0x613a70"/>
    <Procedure i="124151" n="mfem::FiniteElementSpace::RefinementOperator::Mult" v="0x60d740"/>
    <Procedure i="123815" n="mfem::FiniteElementSpace::GetElementDofs" v="0x60ac20"/>
    <Procedure i="123924" n="mfem::Array&lt;int&gt;::~Array()" v="0"/>
    <Procedure i="125853" n="mfem::FiniteElementSpace::GetFE" v="0x616360"/>
    <Procedure i="130309" n="mfem::FiniteElementSpace::Update" v="0x621060"/>
    <Procedure i="126967" n="mfem::FiniteElementSpace::Load" v="0x61a1b0"/>
    <Procedure i="133488" n="mfem::Geometry::Geometry" v="0x6286b8"/>
    <Procedure i="130646" n="mfem::GeometryRefiner::GeometryRefiner" v="0x621c68"/>
    <Procedure i="130457" n="_GLOBAL__sub_I__ZN4mfem8Geometry4NameE" v="0x40baf0"/>
    <Procedure i="130459" n="" v="0"/>
    <Procedure i="130460" n="__static_initialization_and_destruction_0" v="0"/>
    <Procedure i="130462" n="&lt;inline&gt;" f="1" v="0"/>
    <Procedure i="140146" n="mfem::GridFunction::GridFunction" v="0x63be00"/>
    <Procedure i="138042" n="mfem::GridFunction::Update" v="0x638090"/>
    <Procedure i="135033" n="mfem::GridFunction::GetValues" v="0x62d3c8"/>
    <Procedure i="137096" n="mfem::GridFunction::ProjectCoefficient" v="0x6352c8"/>
    <Procedure i="137118" n="" v="0"/>
    <Procedure i="137119" n="mfem::FiniteElementSpace::GetElementTransformation(int) const" v="0"/>
    <Procedure i="137182" n="mfem::GridFunction::ProjectCoefficient" v="0x6355d0"/>
    <Procedure i="137465" n="mfem::GridFunction::operator=" v="0x636120"/>
    <Procedure i="153604" n="mfem::ParBilinearForm::Assemble" v="0x65d900"/>
    <Procedure i="162417" n="mfem::ParFiniteElementSpace::ParFiniteElementSpace" v="0x672ea0"/>
    <Procedure i="162450" n="mfem::ParFiniteElementSpace::ParFiniteElementSpace" v="0x673228"/>
    <Procedure i="162455" n="" v="0"/>
    <Procedure i="162456" n="mfem::FiniteElementSpace::FiniteElementSpace(mfem::Mesh*, mfem::FiniteElementCollection const*, int, int)" v="0"/>
    <Procedure i="162320" n="mfem::ParFiniteElementSpace::ParInit" v="0x672718"/>
    <Procedure i="162342" n="mfem::ParFiniteElementSpace::Construct()" v="0"/>
    <Procedure i="162364" n="mfem::ParFiniteElementSpace::GenerateGlobalOffsets() const" v="0"/>
    <Procedure i="162515" n="mfem::ParFiniteElementSpace::Construct" v="0x673840"/>
    <Procedure i="154632" n="mfem::ParFiniteElementSpace::GetElementDofs" v="0x65f7c0"/>
    <Procedure i="154564" n="mfem::ParFiniteElementSpace::GenerateGlobalOffsets" v="0x65f2b8"/>
    <Procedure i="159371" n="mfem::ParFiniteElementSpace::Build_Dof_TrueDof_Matrix" v="0x66c0e8"/>
    <Procedure i="159648" n="mfem::ParFiniteElementSpace::GetEssentialTrueDofs" v="0x66cb10"/>
    <Procedure i="159670" n="mfem::ParFiniteElementSpace::GetRestrictionMatrix() const" v="0"/>
    <Procedure i="159673" n="mfem::ParFiniteElementSpace::Dof_TrueDof_Matrix() const" v="0"/>
    <Procedure i="156254" n="mfem::ParFiniteElementSpace::Destroy" v="0x666210"/>
    <Procedure i="162548" n="mfem::ParFiniteElementSpace::Update" v="0x6739f0"/>
    <Procedure i="154494" n="mfem::ConformingProlongationOperator::Mult" v="0x65f0d0"/>
    <Procedure i="154508" n="double* std::copy&lt;double const*, double*&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154510" n="double* std::__copy_move_a2&lt;false, double const*, double*&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154512" n="double* std::__copy_move_a&lt;false, double const*, double*&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154514" n="double* std::__copy_move&lt;false, true, std::random_access_iterator_tag&gt;::__copy_m&lt;double&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154529" n="mfem::ConformingProlongationOperator::MultTranspose" v="0x65f1c0"/>
    <Procedure i="162830" n="mfem::ParFiniteElementSpace::~ParFiniteElementSpace" v="0x40eba0"/>
    <Procedure i="163323" n="mfem::ParGridFunction::ParGridFunction" v="0x676d48"/>
    <Procedure i="163132" n="mfem::ParGridFunction::GetValue" v="0x676550"/>
    <Procedure i="163150" n="" v="0"/>