<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.1							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      es	   CDATA #IMPLIED
	      em	   CDATA #IMPLIED
	      ep	   CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.1">
<Header n="laghos">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="laghos">
<SecHeader>
  <MetricTable>
    <Metric i="0" n="CPUTIME (usec).[511,0]" v="raw" em="0" es="0" ep="0" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="1"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" db-glob="*.hpctrace" db-min-time="1560351419991230" db-max-time="1560351496458866" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/gpfs/mira-home/laiwei/applications/laghos/laghos"/>
    <LoadModule i="318019" n="&lt;unknown load module&gt;"/>
    <LoadModule i="318025" n="linux-vdso.so.1"/>
    <LoadModule i="318029" n="/gpfs/mira-home/laiwei/install/hpctoolkit/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="318033" n="/gpfs/mira-home/laiwei/install/hpctoolkit/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="318039" n="/opt/cray/pe/mpt/7.7.3/gni/mpich-gnu/7.1/lib/libmpich_gnu_71.so.3.0.1"/>
    <LoadModule i="318227" n="/lib64/libm-2.22.so"/>
    <LoadModule i="318257" n="/opt/gcc/7.3.0/snos/lib64/libstdc++.so.6.0.24"/>
    <LoadModule i="318313" n="/lib64/libc-2.22.so"/>
    <LoadModule i="318351" n="/lib64/ld-2.22.so"/>
    <LoadModule i="318359" n="/opt/cray/ugni/6.0.14.0-6.0.7.1_3.13__gea11d3d.ari/lib64/libugni.so.0.6.0"/>
    <LoadModule i="318399" n="/opt/cray/pe/pmi/5.0.14/lib64/libpmi.so.0.5.0"/>
  </LoadModuleTable>
  <FileTable>
    <File i="60787" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/hypre-2.10.0b/src/parcsr_mv/new_commpkg.c"/>
    <File i="62523" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/hypre-2.10.0b/src/parcsr_mv/par_csr_communication.c"/>
    <File i="67843" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/hypre-2.10.0b/src/utilities/exchange_data.c"/>
    <File i="68946" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/hypre-2.10.0b/src/utilities/mpistubs.c"/>
    <File i="76295" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/bilinearform.cpp"/>
    <File i="78320" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/bilininteg.cpp"/>
    <File i="79283" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/eltrans.hpp"/>
    <File i="82974" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/coefficient.cpp"/>
    <File i="90060" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/eltrans.cpp"/>
    <File i="93446" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe.cpp"/>
    <File i="103310" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/array.hpp"/>
    <File i="103444" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/vector.hpp"/>
    <File i="104020" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe.hpp"/>
    <File i="120381" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fe_coll.hpp"/>
    <File i="123319" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fespace.cpp"/>
    <File i="123999" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/mesh/mesh.hpp"/>
    <File i="123758" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/fespace.hpp"/>
    <File i="133420" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/gridfunc.cpp"/>
    <File i="151487" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pbilinearform.cpp"/>
    <File i="154171" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pfespace.cpp"/>
    <File i="159342" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pfespace.hpp"/>
    <File i="154191" n="./src/opt/gcc/7.3.0/snos/include/g++/bits/stl_algobase.h"/>
    <File i="162454" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pgridfunc.cpp"/>
    <File i="167928" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/array.cpp"/>
    <File i="171534" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/communication.cpp"/>
    <File i="176278" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/table.hpp"/>
    <File i="174689" n="./src/opt/gcc/7.3.0/snos/include/g++/sstream"/>
    <File i="182796" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/stable3d.cpp"/>
    <File i="183429" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/table.cpp"/>
    <File i="185314" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/tic_toc.cpp"/>
    <File i="185759" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/densemat.cpp"/>
    <File i="186382" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/densemat.hpp"/>
    <File i="196228" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/hypre.cpp"/>
    <File i="203606" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/ode.cpp"/>
    <File i="204511" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/ode.hpp"/>
    <File i="204772" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/operator.cpp"/>
    <File i="206658" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/operator.hpp"/>
    <File i="206709" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/matrix.hpp"/>
    <File i="206818" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/solvers.cpp"/>
    <File i="210391" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/sparsemat.cpp"/>
    <File i="210896" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/mem_alloc.hpp"/>
    <File i="213049" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/sparsemat.hpp"/>
    <File i="217566" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/vector.cpp"/>
    <File i="218189" n="./src/opt/gcc/7.3.0/snos/include/g++/bits/std_abs.h"/>
    <File i="218666" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/mesh/mesh.cpp"/>
    <File i="266832" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/mesh/pmesh.cpp"/>
    <File i="292818" n="./src/gpfs/mira-home/laiwei/applications/laghos/laghos.cpp"/>
    <File i="293309" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/general/communication.hpp"/>
    <File i="295409" n="./src/gpfs/mira-home/laiwei/applications/laghos/laghos_assembly.cpp"/>
    <File i="298343" n="./src/gpfs/mira-home/laiwei/applications/laghos/laghos_assembly.hpp"/>
    <File i="298391" n="./src/gpfs/mira-home/laiwei/applications/laghos/laghos_solver.cpp"/>
    <File i="301081" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/pgridfunc.hpp"/>
    <File i="301084" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/gridfunc.hpp"/>
    <File i="300633" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/linalg/solvers.hpp"/>
    <File i="299177" n="./src/gpfs/mira-home/laiwei/applications/laghos/dependencies/mfem-laghos-v2.0/fem/intrules.hpp"/>
    <File i="299209" n="./src/gpfs/mira-home/laiwei/applications/laghos/laghos_solver.hpp"/>
    <File i="317528" n="&lt;unknown file&gt; [laghos]"/>
    <File i="318020" n="&lt;unknown file&gt;"/>
    <File i="318026" n="&lt;unknown file&gt;"/>
    <File i="318030" n="&lt;unknown file&gt; [libhpcrun.so.0.0.0]"/>
    <File i="318034" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="318040" n="&lt;unknown file&gt; [libmpich_gnu_71.so.3.0.1]"/>
    <File i="318073" n="gni_poll.c"/>
    <File i="318088" n="ch3_progress.c"/>
    <File i="318095" n="bcast.c"/>
    <File i="318124" n="gni_send.c"/>
    <File i="318221" n="finalize.c"/>
    <File i="318224" n="handlemem.c"/>
    <File i="318228" n="&lt;unknown file&gt; [libm-2.22.so]"/>
    <File i="318258" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/new_op.cc"/>
    <File i="318263" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/new_opv.cc"/>
    <File i="318266" n="&lt;unknown file&gt; [libstdc++.so.6.0.24]"/>
    <File i="318269" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/del_opv.cc"/>
    <File i="318273" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/dyncast.cc"/>
    <File i="318276" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/vmi_class_type_info.cc"/>
    <File i="318279" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/typeinfo"/>
    <File i="318282" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/del_op.cc"/>
    <File i="318292" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/class_type_info.cc"/>
    <File i="318303" n="/b/tmp/peint/build-cray-gcc-20180126.202237.011353000/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/libsupc++/../../../../cray-gcc-7.3.0-201801270210.d61239fc6000b/libstdc++-v3/libsupc++/si_class_type_info.cc"/>
    <File i="318314" n="&lt;unknown file&gt; [libc-2.22.so]"/>
    <File i="318352" n="&lt;unknown file&gt; [ld-2.22.so]"/>
    <File i="318360" n="&lt;unknown file&gt; [libugni.so.0.6.0]"/>
    <File i="318400" n="&lt;unknown file&gt; [libpmi.so.0.5.0]"/>
    <File i="318403" n="crtstuff.c"/>
    <File i="318406" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/pmi_core/_pmi_init.c"/>
    <File i="318413" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/pmi_core/smp_barrier.c"/>
    <File i="318421" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/pmi_core/_pmi_rankpid_file.c"/>
    <File i="318424" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/pmi_core/_pmi_allgather.c"/>
    <File i="318430" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/api/misc/pmi_finalize.c"/>
    <File i="318433" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/pmi_core/_pmi_finalize.c"/>
    <File i="318436" n="/notbackedup/users/sko/mpt/mpt_base/pmi/src/pmi_core/_pmi_ft.c"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="60879" n="hypre_NewCommPkgCreate_core" v="0x71c1c0"/>
    <Procedure i="62733" n="hypre_MatvecCommPkgCreate" v="0x71e4b0"/>
    <Procedure i="67873" n="hypre_DataExchangeList" v="0x7493c0"/>
    <Procedure i="69079" n="hypre_MPI_Iprobe" v="0x74d430"/>
    <Procedure i="69084" n="hypre_MPI_Test" v="0x74d450"/>
    <Procedure i="76958" n="mfem::BilinearForm::Assemble" v="0x580120"/>
    <Procedure i="79254" n="mfem::MassIntegrator::AssembleElementMatrix" v="0x64f5c0"/>
    <Procedure i="79282" n="" v="0"/>
    <Procedure i="79283" n="mfem::ElementTransformation::Weight()" v="0"/>
    <Procedure i="80603" n="mfem::VectorMassIntegrator::AssembleElementMatrix" v="0x6540c0"/>
    <Procedure i="83021" n="mfem::FunctionCoefficient::Eval" v="0x63f060"/>
    <Procedure i="82986" n="mfem::GridFunctionCoefficient::Eval" v="0x63eef0"/>
    <Procedure i="83211" n="mfem::VectorFunctionCoefficient::Eval" v="0x63f890"/>
    <Procedure i="90213" n="mfem::ElementTransformation::EvalWeight" v="0x647360"/>
    <Procedure i="90218" n="" v="0"/>
    <Procedure i="90219" n="mfem::ElementTransformation::Jacobian()" v="0"/>
    <Procedure i="90222" n="mfem::IsoparametricTransformation::EvalJacobian()" v="0"/>
    <Procedure i="90093" n="mfem::IsoparametricTransformation::EvalJacobian" v="0x646f40"/>
    <Procedure i="93193" n="mfem::IsoparametricTransformation::Transform" v="0x64c200"/>
    <Procedure i="95531" n="mfem::NodalFiniteElement::Project" v="0x58af60"/>
    <Procedure i="95817" n="mfem::NodalFiniteElement::Project" v="0x58bd80"/>
    <Procedure i="103332" n="mfem::Poly_1D::Basis::Eval" v="0x5ab6d0"/>
    <Procedure i="104062" n="mfem::Poly_1D::Basis::Eval" v="0x5aef70"/>
    <Procedure i="103267" n="mfem::Poly_1D::Binom" v="0x5ab480"/>
    <Procedure i="103309" n="" v="0"/>
    <Procedure i="103310" n="mfem::Array2D&lt;int&gt;::operator[](int)" v="0"/>
    <Procedure i="103315" n="mfem::Poly_1D::CalcBinomTerms" v="0x5ab5f0"/>
    <Procedure i="103425" n="mfem::H1_HexahedronElement::CalcShape" v="0x5ac5d0"/>
    <Procedure i="103444" n="mfem::Vector::operator()(int)" v="0"/>
    <Procedure i="104178" n="mfem::H1_HexahedronElement::CalcDShape" v="0x5b01a0"/>
    <Procedure i="103483" n="mfem::L2_HexahedronElement::CalcShape" v="0x5acd50"/>
    <Procedure i="103996" n="mfem::L2Pos_HexahedronElement::CalcShape" v="0x5aecb0"/>
    <Procedure i="104020" n="mfem::Poly_1D::CalcBernstein(int, double, double*)" v="0"/>
    <Procedure i="104022" n="mfem::Poly_1D::CalcBinomTerms(int, double, double, double*)" v="0"/>
    <Procedure i="120898" n="mfem::H1_FECollection::FiniteElementForGeometry" v="0x6065c0"/>
    <Procedure i="120904" n="mfem::L2_FECollection::FiniteElementForGeometry" v="0x6065f0"/>
    <Procedure i="123994" n="mfem::FiniteElementSpace::GetOrder" v="0x5e7220"/>
    <Procedure i="123998" n="" v="0"/>
    <Procedure i="123999" n="mfem::Mesh::GetElementBaseGeometry(int) const" v="0"/>
    <Procedure i="124002" n="mfem::Array&lt;mfem::Element*&gt;::operator[](int) const" v="0"/>
    <Procedure i="124103" n="mfem::FiniteElementSpace::DofsToVDofs" v="0x5e7e50"/>
    <Procedure i="124149" n="mfem::FiniteElementSpace::GetElementVDofs" v="0x5e8280"/>
    <Procedure i="124154" n="mfem::FiniteElementSpace::DofsToVDofs(mfem::Array&lt;int&gt;&amp;, int) const" v="0"/>
    <Procedure i="124155" n="&lt;inline&gt;" f="1" v="0"/>
    <Procedure i="124160" n="void mfem::Ordering::DofsToVDofs&lt;(mfem::Ordering::Type)0&gt;(int, int, mfem::Array&lt;int&gt;&amp;)" v="0"/>
    <Procedure i="124186" n="mfem::Array&lt;int&gt;::operator[](int)" v="0"/>
    <Procedure i="124192" n="mfem::Array&lt;int&gt;::SetSize(int)" v="0"/>
    <Procedure i="124765" n="mfem::FiniteElementSpace::BuildElementToDofTable" v="0x5ed130"/>
    <Procedure i="123679" n="mfem::FiniteElementSpace::RefinementOperator::Mult" v="0x5e54a0"/>
    <Procedure i="123741" n="mfem::FiniteElementSpace::DofsToVDofs(int, mfem::Array&lt;int&gt;&amp;, int) const" v="0"/>
    <Procedure i="123758" n="int mfem::Ordering::Map&lt;(mfem::Ordering::Type)0&gt;(int, int, int, int)" v="0"/>
    <Procedure i="123325" n="mfem::FiniteElementSpace::GetElementDofs" v="0x5e22f0"/>
    <Procedure i="123442" n="mfem::Array&lt;int&gt;::~Array()" v="0"/>
    <Procedure i="123451" n="mfem::Mesh::GetElementVertices(int, mfem::Array&lt;int&gt;&amp;) const" v="0"/>
    <Procedure i="125495" n="mfem::FiniteElementSpace::GetFE" v="0x5f02c0"/>
    <Procedure i="129928" n="mfem::FiniteElementSpace::Update" v="0x5fbab0"/>
    <Procedure i="137620" n="mfem::GridFunction::Update" v="0x66a6e0"/>
    <Procedure i="137720" n="" v="0"/>
    <Procedure i="137721" n="mfem::Vector::SetSize(int)" v="0"/>
    <Procedure i="137723" n="&lt;inline&gt;" f="1" v="0"/>
    <Procedure i="136699" n="mfem::GridFunction::ProjectCoefficient" v="0x667940"/>
    <Procedure i="136722" n="mfem::FiniteElementSpace::GetElementTransformation(int) const" v="0"/>
    <Procedure i="136779" n="mfem::GridFunction::ProjectCoefficient" v="0x667c60"/>
    <Procedure i="153289" n="mfem::ParBilinearForm::Assemble" v="0x632db0"/>
    <Procedure i="161992" n="mfem::ParFiniteElementSpace::ParFiniteElementSpace" v="0x684210"/>
    <Procedure i="162025" n="mfem::ParFiniteElementSpace::ParFiniteElementSpace" v="0x684590"/>
    <Procedure i="162030" n="" v="0"/>
    <Procedure i="162031" n="mfem::FiniteElementSpace::FiniteElementSpace(mfem::Mesh*, mfem::FiniteElementCollection const*, int, int)" v="0"/>
    <Procedure i="161894" n="mfem::ParFiniteElementSpace::ParInit" v="0x683a50"/>
    <Procedure i="161917" n="mfem::ParFiniteElementSpace::Construct()" v="0"/>
    <Procedure i="161939" n="mfem::ParFiniteElementSpace::GenerateGlobalOffsets() const" v="0"/>
    <Procedure i="162090" n="mfem::ParFiniteElementSpace::Construct" v="0x684bc0"/>
    <Procedure i="154475" n="mfem::ParFiniteElementSpace::GetGroupComm" v="0x6711a0"/>
    <Procedure i="154315" n="mfem::ParFiniteElementSpace::GetElementDofs" v="0x670c80"/>
    <Procedure i="154247" n="mfem::ParFiniteElementSpace::GenerateGlobalOffsets" v="0x670760"/>
    <Procedure i="159320" n="mfem::ParFiniteElementSpace::GetEssentialTrueDofs" v="0x67e190"/>
    <Procedure i="159342" n="mfem::ParFiniteElementSpace::GetRestrictionMatrix() const" v="0"/>
    <Procedure i="159345" n="mfem::ParFiniteElementSpace::Dof_TrueDof_Matrix() const" v="0"/>
    <Procedure i="155416" n="mfem::ParFiniteElementSpace::ConstructTrueDofs" v="0x674b00"/>
    <Procedure i="158585" n="mfem::ParFiniteElementSpace::RebalanceMatrix" v="0x67bf70"/>
    <Procedure i="158605" n="&lt;inline&gt;" f="1" v="0"/>
    <Procedure i="158633" n="mfem::ParFiniteElementSpace::GetLocalTDofNumber(int) const" v="0"/>
    <Procedure i="155905" n="mfem::ParFiniteElementSpace::Destroy" v="0x677880"/>
    <Procedure i="162123" n="mfem::ParFiniteElementSpace::Update" v="0x684d90"/>
    <Procedure i="154177" n="mfem::ConformingProlongationOperator::Mult" v="0x670550"/>
    <Procedure i="154191" n="double* std::copy&lt;double const*, double*&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154193" n="double* std::__copy_move_a2&lt;false, double const*, double*&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154195" n="double* std::__copy_move_a&lt;false, double const*, double*&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154197" n="double* std::__copy_move&lt;false, true, std::random_access_iterator_tag&gt;::__copy_m&lt;double&gt;(double const*, double const*, double*)" v="0"/>
    <Procedure i="154212" n="mfem::ConformingProlongationOperator::MultTranspose" v="0x670650"/>
    <Procedure i="162405" n="mfem::ParFiniteElementSpace::~ParFiniteElementSpace" v="0x40eed0"/>
    <Procedure i="162890" n="mfem::ParGridFunction::ParGridFunction" v="0x688090"/>
    <Procedure i="162699" n="mfem::ParGridFunction::GetValue" v="0x687860"/>
    <Procedure i="162717" n="" v="0"/>
    <Procedure i="162718" n="mfem::Array&lt;int&gt;::Array(int, int)" v="0"/>
    <Procedure i="162721" n="mfem::Array&lt;int&gt;::~Array()" v="0"/>
    <Procedure i="162724" n="mfem::Vector::Vector()" v="0"/>
    <Procedure i="162727" n="mfem::Vector::~Vector()" v="0"/>
    <Procedure i="162759" n="mfem::Vector::SetSize(int)" v="0"/>
    <Procedure i="162499" n="mfem::ParGridFunction::ProjectCoefficient" v="0x686fa0"/>
    <Procedure i="167934" n="mfem::BaseArray::BaseArray" v="0x436580"/>
    <Procedure i="167942" n="mfem::BaseArray::~BaseArray" v="0x4365d0"/>
    <Procedure i="167946" n="mfem::BaseArray::GrowSize" v="0x4365f0"/>
    <Procedure i="172262" n="mfem::GroupTopology::Create" v="0x429f40"/>
    <Procedure i="177592" n="mfem::GroupCommunicator::BcastBegin&lt;double&gt;" v="0x4343c0"/>
    <Procedure i="173465" n="mfem::GroupCommunicator::BcastEnd&lt;double&gt;" v="0x42c5e0"/>
    <Procedure i="173488" n="" v="0"/>
    <Procedure i="173489" n="double const* mfem::GroupCommunicator::CopyGroupFromBuffer&lt;double&gt;(double const*, double*, int, int) const" v="0"/>
    <Procedure i="176229" n="mfem::GroupCommunicator::ReduceBegin&lt;double&gt;" v="0x4317c0"/>
    <Procedure i="176271" n="double* mfem::GroupCommunicator::CopyGroupToBuffer&lt;double&gt;(double const*, double*, int, int) const" v="0"/>
    <Procedure i="176278" n="mfem::Table::RowSize(int) const" v="0"/>
    <Procedure i="174256" n="mfem::GroupCommunicator::ReduceEnd&lt;double&gt;" v="0x42d970"/>
    <Procedure i="174683" n="double const* mfem::GroupCommunicator::ReduceGroupFromBuffer&lt;double&gt;(double const*, double*, int, int, void (*)(mfem::GroupCommunicator::OpData&lt;double&gt;)) const" v="0"/>
    <Procedure i="174689" n="std::__cxx11::basic_ostringstream&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::~basic_ostringstream()" v="0"/>
    <Procedure i="171949" n="mfem::GroupCommunicator::~GroupCommunicator" v="0x429730"/>
    <Procedure i="171956" n="mfem::Array&lt;char&gt;::~Array()" v="0"/>
    <Procedure i="182850" n="mfem::STable3D::Push" v="0x68d810"/>
    <Procedure i="182888" n="mfem::STable3D::operator" v="0x68d990"/>
    <Procedure i="183435" n="mfem::Table::Table" v="0x43e4b0"/>