<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.0							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.0">
<Header n="is.C.O1.32.bupc.infiniband">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="is.C.O1.32.bupc.infiniband">
<SecHeader>
  <MetricTable>
    <Metric i="2" n="WALLCLOCK (us):Sum (I)" v="derived-incr" t="inclusive" partner="3" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($2, $2)"/>
      <MetricFormula t="finalize" frm="$2"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="3" n="WALLCLOCK (us):Sum (E)" v="derived-incr" t="exclusive" partner="2" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($3, $3)"/>
      <MetricFormula t="finalize" frm="$3"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
    <MetricDB i="0" n="WALLCLOCK (us) (I)" db-glob="*.metric-db" db-id="0" db-num-metrics="2" db-header-sz="24"/>
    <MetricDB i="1" n="WALLCLOCK (us) (E)" db-glob="*.metric-db" db-id="1" db-num-metrics="2" db-header-sz="24"/>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" db-glob="*.hpctrace" db-min-time="1339025734315739" db-max-time="1339025741474529" db-header-sz="24"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/dahome/la5/codes/npb-upc-2.4-11.02/bin.C.32/is.C.O1.32"/>
    <LoadModule i="88054" n="/dahome/la5/pkgs/hpctoolkit/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="88064" n="/usr/lib64/libibverbs.so.1.0.0"/>
    <LoadModule i="88068" n="/lib64/libpthread-2.12.so"/>
    <LoadModule i="88072" n="/lib64/librt-2.12.so"/>
    <LoadModule i="88076" n="/opt/apps/openmpi/1.4.4-gcc/lib/libmpi.so.0.0.3"/>
    <LoadModule i="88213" n="/opt/apps/openmpi/1.4.4-gcc/lib/libopen-rte.so.0.0.0"/>
    <LoadModule i="88223" n="/opt/apps/openmpi/1.4.4-gcc/lib/libopen-pal.so.0.0.0"/>
    <LoadModule i="88242" n="/lib64/libc-2.12.so"/>
    <LoadModule i="88246" n="/usr/lib64/libmlx4-m-rdmav2.so"/>
  </LoadModuleTable>
  <FileTable>
    <File i="843" n="./src/dahome/la5/app/bupc/dbg/include/gasnet_trace.h"/>
    <File i="880" n="./src/dahome/la5/app/bupc/dbg/include/ibv-conduit/gasnet_extended.h"/>
    <File i="4339" n="./src/dahome/la5/app/bupc/dbg/include/upcr_shaccess.h"/>
    <File i="7109" n="./src/dahome/la5/codes/npb-upc-2.4-11.02/IS/variants/is-common-2.h"/>
    <File i="7240" n="./src/dahome/la5/codes/npb-upc-2.4-11.02/IS/variants/is.O1.c"/>
    <File i="7758" n="./src/dahome/la5/codes/npb-upc-2.4-11.02/common/upc_timers.h"/>
    <File i="7844" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_coll_autotune.c"/>
    <File i="10586" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_coll_eager.c"/>
    <File i="12050" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_coll_internal.h"/>
    <File i="17063" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_coll_rvous.c"/>
    <File i="18374" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_coll_team.c"/>
    <File i="32704" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_extended_common.c"/>
    <File i="33014" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_extended_refbarrier.c"/>
    <File i="33939" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/extended-ref/gasnet_extended_refcoll.c"/>
    <File i="40641" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_atomicops.h"/>
    <File i="41862" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_coll.h"/>
    <File i="43465" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_help.h"/>
    <File i="44754" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_internal.c"/>
    <File i="46399" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_mmap.c"/>
    <File i="47456" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_pshm.c"/>
    <File i="49004" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_syncops.h"/>
    <File i="50600" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_syncops.h"/>
    <File i="50780" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_syncops.h"/>
    <File i="53536" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/gasnet_tools.c"/>
    <File i="62498" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/other/firehose/firehose.c"/>
    <File i="63830" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/other/firehose/firehose_hash.c"/>
    <File i="63965" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/other/firehose/firehose_region.c"/>
    <File i="65389" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/other/mpi-spawner/gasnet_bootstrap_mpi.c"/>
    <File i="68154" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/vapi-conduit/gasnet_core.c"/>
    <File i="70348" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/vapi-conduit/gasnet_core.h"/>
    <File i="70423" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/vapi-conduit/gasnet_core_connect.c"/>
    <File i="72293" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/vapi-conduit/gasnet_core_sndrcv.c"/>
    <File i="75516" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/vapi-conduit/gasnet_extended.c"/>
    <File i="76449" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/gasnet/vapi-conduit/gasnet_firehose.c"/>
    <File i="77304" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_alloc.c"/>
    <File i="77906" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_alloc.h"/>
    <File i="80118" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_barrier.c"/>
    <File i="80143" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_broadcast.c"/>
    <File i="80161" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_coll_init.c"/>
    <File i="80699" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_init.c"/>
    <File i="87680" n="./src/dahome/la5/pkgs-src/berkeley_upc-2.14.2/upcr_threads.c"/>
    <File i="87827" n="/tmp/upcc-la5-17585-1339024076/is.O1.w2c.h"/>
    <File i="87851" n="/tmp/upcc-la5-17685-1339024078/is.C.O1.32_startup_tmp.c"/>
    <File i="87968" n="./src/usr/include/infiniband/verbs.h"/>
    <File i="88025" n="~unknown-file~"/>
    <File i="88055" n="/dahome/la5/svn/externals/libmonitor/work/src/../../libmonitor-0.x-r124/src/mpi_init_c.c"/>
    <File i="88058" n="/dahome/la5/svn/externals/libmonitor/work/src/../../libmonitor-0.x-r124/src/pthread.c"/>
    <File i="88061" n="/dahome/la5/svn/externals/libmonitor/work/src/../../libmonitor-0.x-r124/src/mpi_final_c.c"/>
    <File i="88065" n="~unknown-file~"/>
    <File i="88069" n="~unknown-file~"/>
    <File i="88073" n="~unknown-file~"/>
    <File i="88077" n="~unknown-file~"/>
    <File i="88080" n="topo_unity_component.c"/>
    <File i="88085" n="pml_ob1_component.c"/>
    <File i="88094" n="btl_openib_component.c"/>
    <File i="88107" n="bml_r2.c"/>
    <File i="88116" n="btl_openib.c"/>
    <File i="88133" n="btl_openib_connect_oob.c"/>
    <File i="88142" n="mpool_rdma_module.c"/>
    <File i="88203" n="ompi_free_list.c"/>
    <File i="88210" n="btl_openib_endpoint.c"/>
    <File i="88214" n="oob_tcp_peer.c"/>
    <File i="88217" n="snapc_base_fns.c"/>
    <File i="88220" n="rml_oob_recv.c"/>
    <File i="88224" n="~unknown-file~"/>
    <File i="88227" n="timer_linux_component.c"/>
    <File i="88230" n="poll.c"/>
    <File i="88239" n="malloc.c"/>
    <File i="88243" n="~unknown-file~"/>
    <File i="88247" n="~unknown-file~"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="844" n="gasneti_trace_setsourceline"/>
    <Procedure i="1641" n="_gasnet_get_bulk"/>
    <Procedure i="5920" n="_upcr_memget"/>
    <Procedure i="7142" n="randlc_is"/>
    <Procedure i="7217" n="create_seq"/>
    <Procedure i="7241" n="full_verify"/>
    <Procedure i="7286" n="upc_reduced_sum"/>
    <Procedure i="7349" n="rank"/>
    <Procedure i="7515" n="user_main"/>
    <Procedure i="7813" n="timer_stop"/>
    <Procedure i="7900" n="gasnete_coll_autotune_register_algorithm"/>
    <Procedure i="7949" n="gasnete_coll_register_broadcast_collectives"/>
    <Procedure i="8423" n="gasnete_coll_register_collectives"/>
    <Procedure i="8455" n="gasnete_coll_autotune_init"/>
    <Procedure i="8638" n="gasnete_coll_get_implementation"/>
    <Procedure i="9747" n="gasnete_coll_autotune_get_bcast_algorithm"/>
    <Procedure i="10637" n="gasnete_coll_pf_bcast_TreeEager"/>
    <Procedure i="12367" n="_gasnete_coll_get_threaddata"/>
    <Procedure i="12494" n="gasnete_coll_generic_insync"/>
    <Procedure i="17193" n="gasnete_coll_pf_bcast_RVous"/>
    <Procedure i="18375" n="initialize_team_fields"/>
    <Procedure i="18457" n="gasnete_coll_team_init"/>
    <Procedure i="32768" n="gasnete_init_threaddata"/>
    <Procedure i="32882" n="gasnete_new_threaddata"/>
    <Procedure i="33098" n="gasnete_pshmbarrier_wait_inner"/>
    <Procedure i="33292" n="gasnete_amdbarrier_kick"/>
    <Procedure i="33390" n="gasnete_amdbarrier_wait"/>
    <Procedure i="33459" n="gasnete_amdbarrier_try"/>
    <Procedure i="33485" n="gasnete_amdbarrier_kick_team_all"/>
    <Procedure i="33791" n="gasnete_coll_barrier_try_internal"/>
    <Procedure i="33802" n="gasnete_coll_barrier_wait_internal"/>
    <Procedure i="33841" n="gasnet_barrier_wait"/>
    <Procedure i="33867" n="gasnet_barrier_try"/>
    <Procedure i="34045" n="gasnete_coll_handle_done"/>
    <Procedure i="34060" n="gasnete_coll_try_sync"/>
    <Procedure i="34150" n="gasnete_coll_sync_saved_handles"/>
    <Procedure i="34184" n="gasnete_coll_active_first"/>
    <Procedure i="34188" n="gasnete_coll_active_next"/>
    <Procedure i="34423" n="gasnete_coll_poll"/>
    <Procedure i="34503" n="gasnete_coll_init"/>
    <Procedure i="35167" n="gasnete_coll_p2p_eager_put_tree"/>
    <Procedure i="35420" n="gasnete_coll_broadcast"/>
    <Procedure i="35427" n="_gasnet_coll_broadcast"/>
    <Procedure i="35973" n="gasnete_coll_broadcast_nb_default"/>
    <Procedure i="40910" n="gasneti_atomic64_read"/>
    <Procedure i="41178" n="gasneti_atomic_read"/>
    <Procedure i="42258" n="gasnete_coll_wait_sync"/>
    <Procedure i="44370" n="gasneti_AMPoll"/>
    <Procedure i="44608" n="gasnet_AMPoll"/>
    <Procedure i="44769" n="gasneti_checkinit"/>
    <Procedure i="44775" n="gasneti_checkattach"/>
    <Procedure i="44978" n="gasneti_setupGlobalEnvironment"/>
    <Procedure i="45357" n="gasneti_nodemap_helper"/>
    <Procedure i="45482" n="gasneti_nodemapInit"/>
    <Procedure i="45694" n="_gasneti_memcheck_one"/>
    <Procedure i="45791" n="_gasneti_memcheck"/>
    <Procedure i="45873" n="_gasneti_malloc_inner"/>
    <Procedure i="45973" n="_gasneti_malloc"/>
    <Procedure i="46046" n="_gasneti_calloc"/>
    <Procedure i="46400" n="gasneti_mmap_internal"/>
    <Procedure i="46435" n="gasneti_mmap"/>
    <Procedure i="46508" n="gasneti_pshm_mmap"/>
    <Procedure i="46595" n="gasneti_mmap_shared_internal"/>
    <Procedure i="46637" n="gasneti_mmap_remote_shared"/>
    <Procedure i="46650" n="gasneti_mmap_shared"/>
    <Procedure i="46683" n="gasneti_munmap"/>
    <Procedure i="46759" n="_gasneti_mmap_segment_search_inner"/>
    <Procedure i="46834" n="gasneti_mmapLimit"/>
    <Procedure i="47023" n="gasneti_segmentAttachLocal"/>
    <Procedure i="47086" n="gasneti_AttachRemote"/>
    <Procedure i="47157" n="gasneti_segmentAttach"/>
    <Procedure i="47335" n="gasneti_auxseg_init"/>
    <Procedure i="47796" n="gasneti_pshmnet_next_msg"/>
    <Procedure i="47878" n="gasneti_pshmnet_recv"/>
    <Procedure i="47928" n="gasneti_pshmnet_bootstrapBarrier"/>
    <Procedure i="48027" n="gasneti_pshmnet_coll_recv"/>
    <Procedure i="48047" n="gasneti_pshmnet_bootstrapBroadcast"/>
    <Procedure i="48388" n="gasneti_AMPSHMPoll"/>
    <Procedure i="49180" n="_gasneti_semaphore_read"/>
    <Procedure i="49205" n="_gasneti_semaphore_up"/>
    <Procedure i="49725" n="gasneti_semaphore_up"/>
    <Procedure i="50493" n="_gasneti_lifo_push"/>
    <Procedure i="50600" n="_gasneti_lifo_push"/>
    <Procedure i="50648" n="_gasneti_lifo_pop"/>
    <Procedure i="50780" n="_gasneti_lifo_pop"/>
    <Procedure i="50991" n="gasneti_lifo_pop"/>
    <Procedure i="51059" n="gasneti_lifo_push"/>
    <Procedure i="54494" n="gasneti_getenv"/>
    <Procedure i="54639" n="_gasneti_getenv_withdefault"/>
    <Procedure i="54685" n="gasneti_getenv_yesno_withdefault"/>
    <Procedure i="54691" n="gasneti_getenv_int_withdefault"/>
    <Procedure i="54809" n="_gasneti_getPhysMemSysconf"/>
    <Procedure i="54816" n="gasneti_getPhysMemSz"/>
    <Procedure i="62499" n="firehose_init"/>
    <Procedure i="62569" n="firehose_fini"/>
    <Procedure i="62615" n="firehose_local_pin"/>
    <Procedure i="62672" n="firehose_try_local_pin"/>
    <Procedure i="62814" n="firehose_remote_pin"/>
    <Procedure i="62884" n="firehose_try_remote_pin"/>
    <Procedure i="63030" n="firehose_release"/>
    <Procedure i="63207" n="fh_priv_acquire_local"/>
    <Procedure i="63267" n="fh_priv_acquire_remote"/>
    <Procedure i="63314" n="fh_priv_release_local"/>
    <Procedure i="63371" n="fh_priv_release_remote"/>
    <Procedure i="63557" n="fh_AdjustLocalFifoAndPin"/>
    <Procedure i="63711" n="fh_am_move_reqh_inner"/>
    <Procedure i="63741" n="fh_am_move_reqh_64"/>
    <Procedure i="63745" n="fh_am_move_reph_inner"/>
    <Procedure i="63812" n="fh_am_move_reph_64"/>
    <Procedure i="63831" n="inthash"/>
    <Procedure i="63842" n="fh_hash_create"/>
    <Procedure i="63862" n="fh_hash_find"/>
    <Procedure i="63899" n="fh_hash_apply"/>
    <Procedure i="64044" n="fh_bucket_lookup"/>
    <Procedure i="64057" n="fh_bucket_hash"/>
    <Procedure i="64145" n="fh_bucket_new"/>
    <Procedure i="64211" n="fh_create_priv"/>
    <Procedure i="64292" n="fh_update_priv"/>
    <Procedure i="64455" n="fhi_init_local_region"/>
    <Procedure i="64536" n="fhi_find_priv"/>
    <Procedure i="64579" n="fh_region_ispinned"/>
    <Procedure i="64616" n="fh_acquire_local_region"/>
    <Procedure i="64708" n="fh_commit_try_local_region"/>
    <Procedure i="64739" n="fh_release_local_region"/>
    <Procedure i="64792" n="fh_acquire_remote_region"/>
    <Procedure i="64929" n="fh_commit_try_remote_region"/>
    <Procedure i="64957" n="fh_release_remote_region"/>
    <Procedure i="64982" n="fh_find_pending_callbacks"/>
    <Procedure i="65038" n="fh_init_plugin"/>
    <Procedure i="65232" n="fh_priv_check_fn"/>
    <Procedure i="65293" n="fh_fini_plugin"/>
    <Procedure i="65318" n="fh_move_request"/>
    <Procedure i="65390" n="gasneti_bootstrapInit_mpi"/>
    <Procedure i="65434" n="gasneti_bootstrapFini_mpi"/>
    <Procedure i="65452" n="gasneti_bootstrapBarrier_mpi"/>
    <Procedure i="65460" n="gasneti_bootstrapExchange_mpi"/>
    <Procedure i="65468" n="gasneti_bootstrapAlltoall_mpi"/>
    <Procedure i="65476" n="gasneti_bootstrapBroadcast_mpi"/>
    <Procedure i="68197" n="gasneti_bootstrapBarrier"/>
    <Procedure i="68280" n="gasneti_bootstrapExchange"/>
    <Procedure i="68340" n="gasnetc_unpin"/>
    <Procedure i="68352" n="gasnetc_pin"/>
    <Procedure i="68373" n="gasnetc_try_pin_inner"/>
    <Procedure i="68394" n="gasnetc_trypin"/>
    <Procedure i="68411" n="gasnetc_init_pin_info"/>
    <Procedure i="68469" n="gasnetc_load_settings"/>
    <Procedure i="68757" n="gasneti_bootstrapInit"/>
    <Procedure i="69093" n="gasnetc_init"/>
    <Procedure i="69274" n="gasnet_init_GASNET_SEQpshmLARGEdebugtracestatsdebugmallocsrclines"/>
    <Procedure i="69324" n="gasnetc_attach"/>
    <Procedure i="69775" n="gasnetc_exit_body"/>
    <Procedure i="69978" n="gasnetc_exit"/>
    <Procedure i="70029" n="gasnetc_AMRequestMediumM"/>
    <Procedure i="70304" n="gasnetc_hsl_unlock"/>
    <Procedure i="70349" n="gasnetc_counter_wait"/>
    <Procedure i="70798" n="gasnetc_qp_reset2init"/>
    <Procedure i="70834" n="gasnetc_qp_init2rtr"/>
    <Procedure i="70876" n="gasnetc_qp_rtr2rts"/>
    <Procedure i="71895" n="gasnetc_connect_static"/>
    <Procedure i="72063" n="gasnetc_connect_init"/>
    <Procedure i="72370" n="gasnetc_create_cq"/>
    <Procedure i="72412" n="gasnetc_fh_aligned_local_pin"/>
    <Procedure i="72583" n="gasnetc_processPacket"/>
    <Procedure i="72849" n="gasnetc_snd_reap"/>
    <Procedure i="73135" n="gasnetc_rcv_am"/>
    <Procedure i="73225" n="gasnetc_rcv_reap"/>
    <Procedure i="73396" n="gasnetc_poll_rcv_hca"/>
    <Procedure i="73423" n="gasnetc_do_poll"/>
    <Procedure i="73478" n="gasnetc_get_bbuf"/>
    <Procedure i="73755" n="gasnetc_ReqRepGeneric"/>
    <Procedure i="74252" n="gasnetc_get_local_fh"/>
    <Procedure i="74377" n="gasnetc_fh_get_helper"/>
    <Procedure i="74574" n="gasnetc_sndrcv_init"/>
    <Procedure i="75040" n="gasnetc_sndrcv_poll"/>
    <Procedure i="75045" n="gasnetc_counter_wait_aux"/>
    <Procedure i="75113" n="gasnetc_rdma_get"/>
    <Procedure i="75162" n="gasnetc_RequestGeneric"/>
    <Procedure i="75299" n="gasnetc_AMPoll"/>
    <Procedure i="75631" n="gasnete_iop_new"/>
    <Procedure i="76051" n="gasnete_init"/>
    <Procedure i="76404" n="gasnete_get_bulk"/>
    <Procedure i="76450" n="firehose_move_callback"/>
    <Procedure i="77443" n="upcri_init_heaps"/>
    <Procedure i="77750" n="_upcr_all_alloc"/>
    <Procedure i="77987" n="upcri_checkmalloc"/>
    <Procedure i="80125" n="_upcr_wait"/>
    <Procedure i="80132" n="_upcr_try_wait"/>
    <Procedure i="80148" n="_upcri_broadcast"/>
    <Procedure i="80162" n="upcri_coll_init"/>
    <Procedure i="80810" n="upcri_startup_messages"/>
    <Procedure i="80886" n="upcr_startup_init"/>
    <Procedure i="80929" n="upcr_startup_attach"/>
    <Procedure i="81122" n="upcri_perthread_spawn"/>
    <Procedure i="81225" n="upcr_startup_spawn"/>
    <Procedure i="81253" n="upcri_finalbarrier"/>
    <Procedure i="81337" n="upcr_global_exit"/>
    <Procedure i="81359" n="upcri_do_exit"/>
    <Procedure i="81392" n="do_bupc_init_reentrant"/>
    <Procedure i="81424" n="bupc_init_reentrant"/>
    <Procedure i="81530" n="_upcr_startup_pshalloc"/>
    <Procedure i="87681" n="upcri_stack_check"/>
    <Procedure i="87828" n="UPCRI_ALLOC_is_O1_2786089158"/>
    <Procedure i="87852" n="perfile_allocs"/>
    <Procedure i="87860" n="static_init"/>
    <Procedure i="87923" n="main"/>
    <Procedure i="87976" n="ibv_poll_cq"/>
    <Procedure i="88026" n=".plt"/>
    <Procedure i="88056" n="MPI_Init"/>
    <Procedure i="88059" n="pthread_create"/>
    <Procedure i="88062" n="MPI_Finalize"/>
    <Procedure i="88066" n="~unknown-proc~"/>
    <Procedure i="88070" n="~unknown-proc~"/>
    <Procedure i="88074" n="~unknown-proc~"/>
    <Procedure i="88078" n="PMPI_Init"/>
    <Procedure i="88083" n="mca_pml_base_select"/>
    <Procedure i="88088" n="mca_bml_base_init"/>
    <Procedure i="88092" n="mca_btl_base_select"/>
    <Procedure i="88103" n="ompi_bitmap_init"/>
    <Procedure i="88105" n="~unknown-proc~"/>
    <Procedure i="88119" n="PMPI_Comm_create"/>
    <Procedure i="88123" n="ompi_comm_nextcid"/>
    <Procedure i="88138" n="ompi_free_list_grow"/>
    <Procedure i="88161" n="PMPI_Bcast"/>
    <Procedure i="88177" n="MPI_Allgather"/>
    <Procedure i="88181" n="PMPI_Alltoall"/>
    <Procedure i="88185" n="ompi_ddt_copy_content_same_ddt"/>
    <Procedure i="88187" n="PMPI_Barrier"/>
    <Procedure i="88197" n="mca_btl_base_close"/>
    <Procedure i="88081" n="ompi_mpi_init"/>
    <Procedure i="88090" n="mca_bml_r2_component_init"/>
    <Procedure i="88097" n="ompi_btl_openib_fd_init"/>
    <Procedure i="88101" n="mca_pml_ob1_add_procs"/>
    <Procedure i="88110" n="mca_btl_tcp_add_procs"/>
    <Procedure i="88112" n="mca_btl_tcp_proc_insert"/>
    <Procedure i="88114" n="mca_btl_openib_add_procs"/>
    <Procedure i="88121" n="ompi_comm_create"/>
    <Procedure i="88125" n="ompi_coll_tuned_allreduce_intra_recursivedoubling"/>
    <Procedure i="88127" n="mca_pml_ob1_isend"/>
    <Procedure i="88129" n="mca_pml_ob1_send_request_start_copy"/>
    <Procedure i="88131" n="mca_btl_openib_endpoint_send"/>
    <Procedure i="88136" n="mca_btl_openib_endpoint_post_recvs"/>
    <Procedure i="88140" n="mca_mpool_rdma_alloc"/>
    <Procedure i="88147" n="mca_btl_openib_post_srr"/>
    <Procedure i="88149" n="ompi_request_default_wait_all"/>
    <Procedure i="88159" n="mca_btl_sm_component_progress"/>
    <Procedure i="88163" n="mca_coll_sync_bcast"/>
    <Procedure i="88165" n="ompi_coll_tuned_bcast_intra_dec_fixed"/>
    <Procedure i="88167" n="ompi_coll_tuned_bcast_intra_split_bintree"/>
    <Procedure i="88169" n="mca_pml_ob1_progress"/>
    <Procedure i="88171" n="mca_pml_ob1_send"/>
    <Procedure i="88173" n="mca_pml_ob1_recv"/>
    <Procedure i="88175" n="ompi_coll_tuned_sendrecv_actual"/>
    <Procedure i="88179" n="ompi_coll_tuned_allgather_intra_recursivedoubling"/>
    <Procedure i="88183" n="ompi_coll_tuned_alltoall_intra_bruck"/>
    <Procedure i="88189" n="ompi_coll_tuned_barrier_intra_recursivedoubling"/>
    <Procedure i="88191" n="ompi_mpi_finalize"/>
    <Procedure i="88195" n="mca_bml_r2_finalize"/>
    <Procedure i="88199" n="mca_btl_openib_finalize"/>
    <Procedure i="88206" n="mca_mpool_rdma_free"/>
    <Procedure i="88086" n="mca_pml_ob1_component_init"/>
    <Procedure i="88193" n="mca_pml_ob1_component_fini"/>
    <Procedure i="88095" n="btl_openib_component_init"/>
    <Procedure i="88099" n="prepare_device_for_use"/>
    <Procedure i="88145" n="openib_reg_mr"/>
    <Procedure i="88151" n="btl_openib_component_progress"/>
    <Procedure i="88201" n="device_destruct"/>
    <Procedure i="88208" n="openib_dereg_mr"/>
    <Procedure i="88108" n="mca_bml_r2_add_procs"/>
    <Procedure i="88117" n="adjust_cq"/>
    <Procedure i="88134" n="oob_module_start_connect"/>
    <Procedure i="88153" n="rml_recv_cb"/>
    <Procedure i="88155" n="qp_connect_all"/>
    <Procedure i="88157" n="qp_create_one"/>
    <Procedure i="88143" n="register_cache_bypass"/>
    <Procedure i="88204" n="ompi_free_list_destruct"/>
    <Procedure i="88211" n="mca_btl_openib_endpoint_destruct"/>
    <Procedure i="88215" n="mca_oob_tcp_peer_recv_handler"/>
    <Procedure i="88218" n="mca_oob_tcp_msg_recv_complete"/>
    <Procedure i="88221" n="orte_rml_recv_msg_callback"/>
    <Procedure i="88225" n="opal_progress"/>
    <Procedure i="88233" n="opal_mem_free_ptmalloc2_munmap"/>
    <Procedure i="88237" n="opal_memory_ptmalloc2_int_malloc"/>
    <Procedure i="88228" n="opal_event_base_loop"/>
    <Procedure i="88235" n="opal_memory_ptmalloc2_malloc"/>
    <Procedure i="88231" n="poll_dispatch"/>
    <Procedure i="88240" n="opal_memory_ptmalloc2_free_hook"/>
    <Procedure i="88244" n="~unknown-proc~"/>