<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.2							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   o: metric sequence order (hpcrun metric order) -->
    <!--   md: metric description -->
    <!--   mp: metric parent ID   -->
    <!--   es: number of samples    (perf_events only) -->
    <!--   em: event multiplexed    (perf_events only) -->
    <!--   ep: average event period (perf_events only) -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric      -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      o	           CDATA #IMPLIED
	      n            CDATA #REQUIRED
	      md	       CDATA #IMPLIED
	      mp	       CDATA #IMPLIED
	      es	       CDATA #IMPLIED
	      em	       CDATA #IMPLIED
	      ep	       CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize|view) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   u: unit time of the trace (ms, ns, ..) -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      u            CDATA #IMPLIED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.2">
<Header n="a.out">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="a.out">
<SecHeader>
  <MetricTable>
    <Metric i="15486" n="CPUTIME (s):Sum (I)" o="0" v="derived-incr" md="CPUTIME (s)" em="0" es="0" ep="0" t="inclusive" partner="15487" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15486, $15486)"/>
      <MetricFormula t="finalize" frm="$15486"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15487" n="CPUTIME (s):Sum (E)" o="-1" v="derived-incr" md="CPUTIME (s)" em="0" es="0" ep="0" t="exclusive" partner="15486" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15487, $15487)"/>
      <MetricFormula t="finalize" frm="$15487"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15488" n="GKER (s):Sum (I)" o="0" v="derived-incr" md="GPU time: kernel execution (seconds)" em="0" es="0" ep="0" t="inclusive" partner="15489" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15488, $15488)"/>
      <MetricFormula t="finalize" frm="$15488"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15489" n="GKER (s):Sum (E)" o="-1" v="derived-incr" md="GPU time: kernel execution (seconds)" em="0" es="0" ep="0" t="exclusive" partner="15488" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15489, $15489)"/>
      <MetricFormula t="finalize" frm="$15489"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15490" n="GMEM (s):Sum (I)" o="1" v="derived-incr" md="GPU time: memory allocation/deallocation (seconds)" em="0" es="0" ep="0" t="inclusive" partner="15491" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15490, $15490)"/>
      <MetricFormula t="finalize" frm="$15490"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15491" n="GMEM (s):Sum (E)" o="-1" v="derived-incr" md="GPU time: memory allocation/deallocation (seconds)" em="0" es="0" ep="0" t="exclusive" partner="15490" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15491, $15491)"/>
      <MetricFormula t="finalize" frm="$15491"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15492" n="GMSET (s):Sum (I)" o="2" v="derived-incr" md="GPU time: memory set (seconds)" em="0" es="0" ep="0" t="inclusive" partner="15493" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15492, $15492)"/>
      <MetricFormula t="finalize" frm="$15492"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15493" n="GMSET (s):Sum (E)" o="-1" v="derived-incr" md="GPU time: memory set (seconds)" em="0" es="0" ep="0" t="exclusive" partner="15492" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15493, $15493)"/>
      <MetricFormula t="finalize" frm="$15493"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15494" n="GXCOPY (s):Sum (I)" o="3" v="derived-incr" md="GPU time: explicit data copy (seconds)" em="0" es="0" ep="0" t="inclusive" partner="15495" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15494, $15494)"/>
      <MetricFormula t="finalize" frm="$15494"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15495" n="GXCOPY (s):Sum (E)" o="-1" v="derived-incr" md="GPU time: explicit data copy (seconds)" em="0" es="0" ep="0" t="exclusive" partner="15494" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15495, $15495)"/>
      <MetricFormula t="finalize" frm="$15495"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15496" n="GICOPY (s):Sum (I)" o="4" v="derived-incr" md="GPU time: implicit data copy (seconds)" em="0" es="0" ep="0" t="inclusive" partner="15497" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15496, $15496)"/>
      <MetricFormula t="finalize" frm="$15496"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15497" n="GICOPY (s):Sum (E)" o="-1" v="derived-incr" md="GPU time: implicit data copy (seconds)" em="0" es="0" ep="0" t="exclusive" partner="15496" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15497, $15497)"/>
      <MetricFormula t="finalize" frm="$15497"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15498" n="GSYNC (s):Sum (I)" o="5" v="derived-incr" md="GPU time: synchronization (seconds)" em="0" es="0" ep="0" t="inclusive" partner="15499" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15498, $15498)"/>
      <MetricFormula t="finalize" frm="$15498"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15499" n="GSYNC (s):Sum (E)" o="-1" v="derived-incr" md="GPU time: synchronization (seconds)" em="0" es="0" ep="0" t="exclusive" partner="15498" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15499, $15499)"/>
      <MetricFormula t="finalize" frm="$15499"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15500" n="GMEM:UNK (B):Sum (I)" o="6" v="derived-incr" md="GPU memory alloc/free: unknown memory kind (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15501" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15500, $15500)"/>
      <MetricFormula t="finalize" frm="$15500"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15501" n="GMEM:UNK (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: unknown memory kind (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15500" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15501, $15501)"/>
      <MetricFormula t="finalize" frm="$15501"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15502" n="GMEM:PAG (B):Sum (I)" o="7" v="derived-incr" md="GPU memory alloc/free: pageable memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15503" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15502, $15502)"/>
      <MetricFormula t="finalize" frm="$15502"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15503" n="GMEM:PAG (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: pageable memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15502" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15503, $15503)"/>
      <MetricFormula t="finalize" frm="$15503"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15504" n="GMEM:PIN (B):Sum (I)" o="8" v="derived-incr" md="GPU memory alloc/free: pinned memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15505" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15504, $15504)"/>
      <MetricFormula t="finalize" frm="$15504"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15505" n="GMEM:PIN (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: pinned memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15504" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15505, $15505)"/>
      <MetricFormula t="finalize" frm="$15505"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15506" n="GMEM:DEV (B):Sum (I)" o="9" v="derived-incr" md="GPU memory alloc/free: device memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15507" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15506, $15506)"/>
      <MetricFormula t="finalize" frm="$15506"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15507" n="GMEM:DEV (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: device memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15506" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15507, $15507)"/>
      <MetricFormula t="finalize" frm="$15507"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15508" n="GMEM:ARY (B):Sum (I)" o="10" v="derived-incr" md="GPU memory alloc/free: array memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15509" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15508, $15508)"/>
      <MetricFormula t="finalize" frm="$15508"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15509" n="GMEM:ARY (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: array memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15508" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15509, $15509)"/>
      <MetricFormula t="finalize" frm="$15509"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15510" n="GMEM:MAN (B):Sum (I)" o="11" v="derived-incr" md="GPU memory alloc/free: managed memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15511" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15510, $15510)"/>
      <MetricFormula t="finalize" frm="$15510"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15511" n="GMEM:MAN (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: managed memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15510" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15511, $15511)"/>
      <MetricFormula t="finalize" frm="$15511"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15512" n="GMEM:DST (B):Sum (I)" o="12" v="derived-incr" md="GPU memory alloc/free: device static memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15513" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15512, $15512)"/>
      <MetricFormula t="finalize" frm="$15512"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15513" n="GMEM:DST (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: device static memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15512" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15513, $15513)"/>
      <MetricFormula t="finalize" frm="$15513"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15514" n="GMEM:MST (B):Sum (I)" o="13" v="derived-incr" md="GPU memory alloc/free: managed static memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15515" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15514, $15514)"/>
      <MetricFormula t="finalize" frm="$15514"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15515" n="GMEM:MST (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: managed static memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15514" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15515, $15515)"/>
      <MetricFormula t="finalize" frm="$15515"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15516" n="GMEM:COUNT:Sum (I)" o="14" v="derived-incr" md="GPU memory alloc/free: count" em="0" es="0" ep="0" t="inclusive" partner="15517" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15516, $15516)"/>
      <MetricFormula t="finalize" frm="$15516"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15517" n="GMEM:COUNT:Sum (E)" o="-1" v="derived-incr" md="GPU memory alloc/free: count" em="0" es="0" ep="0" t="exclusive" partner="15516" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15517, $15517)"/>
      <MetricFormula t="finalize" frm="$15517"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15518" n="GMSET:UNK (B):Sum (I)" o="15" v="derived-incr" md="GPU memory set: unknown memory kind (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15519" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15518, $15518)"/>
      <MetricFormula t="finalize" frm="$15518"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15519" n="GMSET:UNK (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: unknown memory kind (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15518" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15519, $15519)"/>
      <MetricFormula t="finalize" frm="$15519"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15520" n="GMSET:PAG (B):Sum (I)" o="16" v="derived-incr" md="GPU memory set: pageable memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15521" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15520, $15520)"/>
      <MetricFormula t="finalize" frm="$15520"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15521" n="GMSET:PAG (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: pageable memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15520" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15521, $15521)"/>
      <MetricFormula t="finalize" frm="$15521"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15522" n="GMSET:PIN (B):Sum (I)" o="17" v="derived-incr" md="GPU memory set: pinned memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15523" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15522, $15522)"/>
      <MetricFormula t="finalize" frm="$15522"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15523" n="GMSET:PIN (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: pinned memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15522" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15523, $15523)"/>
      <MetricFormula t="finalize" frm="$15523"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15524" n="GMSET:DEV (B):Sum (I)" o="18" v="derived-incr" md="GPU memory set: device memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15525" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15524, $15524)"/>
      <MetricFormula t="finalize" frm="$15524"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15525" n="GMSET:DEV (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: device memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15524" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15525, $15525)"/>
      <MetricFormula t="finalize" frm="$15525"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15526" n="GMSET:ARY (B):Sum (I)" o="19" v="derived-incr" md="GPU memory set: array memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15527" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15526, $15526)"/>
      <MetricFormula t="finalize" frm="$15526"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15527" n="GMSET:ARY (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: array memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15526" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15527, $15527)"/>
      <MetricFormula t="finalize" frm="$15527"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15528" n="GMSET:MAN (B):Sum (I)" o="20" v="derived-incr" md="GPU memory set: managed memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15529" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15528, $15528)"/>
      <MetricFormula t="finalize" frm="$15528"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15529" n="GMSET:MAN (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: managed memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15528" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15529, $15529)"/>
      <MetricFormula t="finalize" frm="$15529"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15530" n="GMSET:DST (B):Sum (I)" o="21" v="derived-incr" md="GPU memory set: device static memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15531" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15530, $15530)"/>
      <MetricFormula t="finalize" frm="$15530"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15531" n="GMSET:DST (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: device static memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15530" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15531, $15531)"/>
      <MetricFormula t="finalize" frm="$15531"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15532" n="GMSET:MST (B):Sum (I)" o="22" v="derived-incr" md="GPU memory set: managed static memory (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15533" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15532, $15532)"/>
      <MetricFormula t="finalize" frm="$15532"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15533" n="GMSET:MST (B):Sum (E)" o="-1" v="derived-incr" md="GPU memory set: managed static memory (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15532" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15533, $15533)"/>
      <MetricFormula t="finalize" frm="$15533"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15534" n="GMSET:COUNT:Sum (I)" o="23" v="derived-incr" md="GPU memory set: count" em="0" es="0" ep="0" t="inclusive" partner="15535" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15534, $15534)"/>
      <MetricFormula t="finalize" frm="$15534"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15535" n="GMSET:COUNT:Sum (E)" o="-1" v="derived-incr" md="GPU memory set: count" em="0" es="0" ep="0" t="exclusive" partner="15534" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15535, $15535)"/>
      <MetricFormula t="finalize" frm="$15535"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15536" n="GXCOPY:UNK (B):Sum (I)" o="24" v="derived-incr" md="GPU explicit memory copy: unknown kind (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15537" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15536, $15536)"/>
      <MetricFormula t="finalize" frm="$15536"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15537" n="GXCOPY:UNK (B):Sum (E)" o="-1" v="derived-incr" md="GPU explicit memory copy: unknown kind (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15536" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15537, $15537)"/>
      <MetricFormula t="finalize" frm="$15537"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15538" n="GXCOPY:H2D (B):Sum (I)" o="25" v="derived-incr" md="GPU explicit memory copy: host to device (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15539" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15538, $15538)"/>
      <MetricFormula t="finalize" frm="$15538"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15539" n="GXCOPY:H2D (B):Sum (E)" o="-1" v="derived-incr" md="GPU explicit memory copy: host to device (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15538" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15539, $15539)"/>
      <MetricFormula t="finalize" frm="$15539"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15540" n="GXCOPY:D2H (B):Sum (I)" o="26" v="derived-incr" md="GPU explicit memory copy: device to host (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15541" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15540, $15540)"/>
      <MetricFormula t="finalize" frm="$15540"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15541" n="GXCOPY:D2H (B):Sum (E)" o="-1" v="derived-incr" md="GPU explicit memory copy: device to host (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15540" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15541, $15541)"/>
      <MetricFormula t="finalize" frm="$15541"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15542" n="GXCOPY:H2A (B):Sum (I)" o="27" v="derived-incr" md="GPU explicit memory copy: host to array (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15543" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15542, $15542)"/>
      <MetricFormula t="finalize" frm="$15542"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15543" n="GXCOPY:H2A (B):Sum (E)" o="-1" v="derived-incr" md="GPU explicit memory copy: host to array (bytes)" em="0" es="0" ep="0" t="exclusive" partner="15542" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15543, $15543)"/>
      <MetricFormula t="finalize" frm="$15543"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="15544" n="GXCOPY:A2H (B):Sum (I)" o="28" v="derived-incr" md="GPU explicit memory copy: array to host (bytes)" em="0" es="0" ep="0" t="inclusive" partner="15545" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($15544, $15544)"/>
      <MetricFormula t="finalize" frm="$15544"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>